### ISSUE TITLE
Выдает ошибку

### ISSUE THREAD

**Issue by 3DOSES** [dpashtet/telegram-shop#2]
C:\Users\iliab\OneDrive\Рабочий стол\telegram-shop-master>py main.py
Traceback (most recent call last):
  File "C:\Users\iliab\OneDrive\Рабочий стол\telegram-shop-master\main.py", line 2, in <module>
    import config, dop, payments, adminka, files
  File "C:\Users\iliab\OneDrive\Рабочий стол\telegram-shop-master\dop.py", line 4, in <module>
    from coinbase.wallet.client import Client
ModuleNotFoundError: No module named 'coinbase'

**Comment by dpashtet** [comment]
pip install coinbase
